version: '2'
services:
    ioe-mysql:
        container_name: ioe-mysql
        image: mysql:5.7.12
        # volumes:
        #     - ~/volumes/jhipster/ioe/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=ioe
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=ioe
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
